
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.JSONObject;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class CekCuacaView extends javax.swing.JFrame {
    private ArrayList<String> kotaFavorit = new ArrayList<>();
    private final String apiKey = "8bf9a32d8fb8394abfbf36e9debdb472"; // Ganti dengan API key yang valid


    /**
     * Creates new form CekCuacaView
     */
    public CekCuacaView() {
        initComponents();
        
        
        
        
        
        loadKotaFavoritFromFile();  // Load kota favorit saat aplikasi dimulai
    DefaultTableModel tableModel = new DefaultTableModel();
    tableModel.addColumn("Kota");
    tableModel.addColumn("Cuaca");
    tableModel.addColumn("Suhu");
    jTable2.setModel(tableModel);
           
    }
    
    private void saveKotaFavoritToFile() {
    try (BufferedWriter writer = new BufferedWriter(new FileWriter("kotaFavorit.txt"))) {
        for (String kota : kotaFavorit) {
            writer.write(kota);
            writer.newLine();
        }
    } catch (IOException e) {
        e.printStackTrace();
    }
}
    
    private void loadKotaFavoritFromFile() {
    kotaFavorit.clear();  // Clear existing data
    try (BufferedReader reader = new BufferedReader(new FileReader("kotaFavorit.txt"))) {
        String line;
        while ((line = reader.readLine()) != null) {
            kotaFavorit.add(line);
        }
    } catch (IOException e) {
        e.printStackTrace();
    }
    updateKotaFavoritComboBox();  // Update ComboBox after loading
}
    
    // Fungsi untuk mengambil data cuaca dari API
    private String getWeatherData(String kota) {
        try {
            String urlString = "https://api.openweathermap.org/data/2.5/weather?q=" + kota + "&appid=" + apiKey;
            URL url = new URL(urlString);
            HttpURLConnection conn = (HttpURLConnection) url.openConnection();
            conn.setRequestMethod("GET");

            Scanner scanner = new Scanner(url.openStream());
            String response = scanner.useDelimiter("\\A").next();
            scanner.close();

            JSONObject jsonObject = new JSONObject(response);
            String kondisiCuaca = jsonObject.getJSONArray("weather").getJSONObject(0).getString("description");
            double suhu = jsonObject.getJSONObject("main").getDouble("temp") - 273.15; // Konversi dari Kelvin ke Celsius

     
            return "Kota: " + kota + "\nCuaca: " + kondisiCuaca + "\nSuhu: " + String.format("%.2f", suhu) + "°C";
        } catch (Exception ex) {
            ex.printStackTrace();
            return "Error: Gagal mendapatkan data cuaca.";
            
        }
        
        
    }

    // Fungsi untuk memperbarui daftar kota favorit di ComboBox
    private void updateKotaFavoritComboBox() {
        jComboBoxKotaFavorit.removeAllItems();
        for (String kota : kotaFavorit) {
            jComboBoxKotaFavorit.addItem(kota);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldKota = new javax.swing.JTextField();
        btnCekCuaca = new javax.swing.JButton();
        btnUlang = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnFavorit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jComboBoxKotaFavorit = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setText("Masukkan Kota :");

        jLabel2.setText("Kota Favorit :");

        jTextFieldKota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldKotaActionPerformed(evt);
            }
        });

        btnCekCuaca.setText("Cek");
        btnCekCuaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekCuacaActionPerformed(evt);
            }
        });

        btnUlang.setText("Ulang");
        btnUlang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUlangActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        btnFavorit.setText("Tambahkan Ke Favorit");
        btnFavorit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFavoritActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jComboBoxKotaFavorit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banjarbaru", "Surabaya", "Jakarta", "Bandung", "Semarang" }));
        jComboBoxKotaFavorit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxKotaFavoritActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldKota)
                                    .addComponent(jComboBoxKotaFavorit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(btnCekCuaca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUlang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFavorit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKeluar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxKotaFavorit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCekCuaca)
                    .addComponent(btnUlang)
                    .addComponent(btnSimpan)
                    .addComponent(btnKeluar)
                    .addComponent(btnFavorit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 385, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCekCuacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekCuacaActionPerformed
        // TODO add your handling code here:
    String kota = jTextFieldKota.getText().trim();
    if (kota.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Masukkan nama kota terlebih dahulu.");
        return;
    }
    
    String hasilCuaca = getWeatherData(kota);
    jTextArea1.setText(hasilCuaca);
    
    // Menambahkan data cuaca ke tabel
    DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
    model.addRow(new Object[]{kota, hasilCuaca.split("\n")[1], hasilCuaca.split("\n")[2]});

    // Menentukan gambar cuaca sesuai dengan kondisi cuaca
    String kondisiCuaca = hasilCuaca.split("\n")[1].toLowerCase();
    String imagePath = "";
    
    if (kondisiCuaca.contains("clear") || kondisiCuaca.contains("sunny")) {
        imagePath = "images/sunny.png"; // Gambar cuaca cerah
    } else if (kondisiCuaca.contains("cloudy") || kondisiCuaca.contains("overcast")) {
        imagePath = "images/cloudy.png"; // Gambar cuaca mendung
    } else if (kondisiCuaca.contains("rain")) {
        imagePath = "images/rainy.png"; // Gambar cuaca hujan
    } else if (kondisiCuaca.contains("snow")) {
        imagePath = "images/snowy.png"; // Gambar cuaca salju
    } else {
        imagePath = "images/default.png"; // Gambar default
    }

    // Menampilkan gambar cuaca di JLabel
    JLabel weatherImageLabel = new JLabel(new ImageIcon(imagePath));
    jPanel1.add(weatherImageLabel); // Menambahkan JLabel ke panel utama
    jPanel1.revalidate();
    jPanel1.repaint();
    }//GEN-LAST:event_btnCekCuacaActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnFavoritActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFavoritActionPerformed
        // TODO add your handling code here:
String kota = jTextFieldKota.getText().trim();
    if (kota.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Masukkan nama kota terlebih dahulu.");
        return;
    }

    if (!kotaFavorit.contains(kota)) {
        kotaFavorit.add(kota);
        saveKotaFavoritToFile();  // Save the updated list to file
        updateKotaFavoritComboBox();
        JOptionPane.showMessageDialog(this, "Kota " + kota + " berhasil ditambahkan ke favorit.");
    } else {
        JOptionPane.showMessageDialog(this, "Kota sudah ada di daftar favorit.");
    }
        
        
    }//GEN-LAST:event_btnFavoritActionPerformed

    private void jComboBoxKotaFavoritActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxKotaFavoritActionPerformed
        // TODO add your handling code here:
String kota = (String) jComboBoxKotaFavorit.getSelectedItem();
        if (kota != null) {
            String hasilCuaca = getWeatherData(kota);
            jTextArea1.setText(hasilCuaca);
        }
    }//GEN-LAST:event_jComboBoxKotaFavoritActionPerformed

    private void btnUlangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUlangActionPerformed
        // TODO add your handling code here:
        // Reset TextField dan TextArea
    jTextFieldKota.setText("");  // Kosongkan TextField input kota
    jTextArea1.setText("");       // Kosongkan TextArea output cuaca
    
    // Kosongkan tabel jika ada data yang ditampilkan
    DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
    model.setRowCount(0);  // Menghapus semua baris dari tabel
    }//GEN-LAST:event_btnUlangActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
      // Membuka JFileChooser untuk memilih lokasi dan nama file
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Pilih Lokasi untuk Menyimpan File");
    fileChooser.setSelectedFile(new java.io.File("dataCuaca.csv")); // Menetapkan nama file default

    // Memunculkan dialog Simpan
    int result = fileChooser.showSaveDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
        // Mendapatkan file yang dipilih pengguna
        java.io.File file = fileChooser.getSelectedFile();
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {
            // Tulis header CSV
            writer.write("Kota,Cuaca,Suhu");
            writer.newLine();

            // Ambil data dari tabel dan tulis ke dalam file CSV
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            for (int i = 0; i < model.getRowCount(); i++) {
                String kota = (String) model.getValueAt(i, 0);
                String cuaca = (String) model.getValueAt(i, 1);
                String suhu = (String) model.getValueAt(i, 2);

                // Tulis baris data
                writer.write(kota + "," + cuaca + "," + suhu);
                writer.newLine();
            }

            JOptionPane.showMessageDialog(this, "Data cuaca berhasil disimpan ke CSV.");
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menyimpan data ke CSV.");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Penyimpanan dibatalkan.");
    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void jTextFieldKotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldKotaActionPerformed
s        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldKotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CekCuacaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CekCuacaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CekCuacaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CekCuacaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CekCuacaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCekCuaca;
    private javax.swing.JButton btnFavorit;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUlang;
    private javax.swing.JComboBox<String> jComboBoxKotaFavorit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldKota;
    // End of variables declaration//GEN-END:variables
}
